[tool.poetry]
name = "django-event-store"
version = "0.1.0"
description = "Python event store"
authors = ["Michal Godkowicz <michal.godkowicz@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
